### ISSUE TITLE
FAQ not getting displayed

### ISSUE THREAD

**Issue by shwetsolanki** [freshdesk/hotline-ios#1]
I have integrated the hotline sdk using Cocoapods in a Swift Application. I am able to present conversations and faq. Conversations is fully functional, but the FAQ categories which I added on the dashboard are not visible on the app. I have added couple of FAQs as well to the category.

**Comment by hrishikesh-p** [comment]
Can you please check the visibility of the FAQs added ? The default status for FAQs is draft . You will need to switch them to Published to be visible in the SDK . 

Also , we don't show categories that don't have any visible Articles . Please check and let us know .

**Comment by shwetsolanki** [comment]
Thanks, Draft was the issue. I have another question, we have 2 iOS apps and lots of FAQs are similar and few of them are different. Is there a way through which I can send which FAQ Categories I want to show for a particular app? or creating a new app on Hotline is the only option.

**Comment by hrishikesh-p** [comment]
You can only add FAQs for a single App. The app can have multiple platforms and you can control which articles show up on Android Vs iOS versions of the Same app . 

So for 2 iOS apps. the solution is to have 2 accounts .

**Comment by kaushaldream11** [comment]
I am getting this crash in Hotline sdk.

Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFSet: 0x7aea03e0> was mutated while being enumerated.'
*** First throw call stack:
(
0   CoreFoundation                      0x01d82a14 __exceptionPreprocess + 180
1   libobjc.A.dylib                     0x0497fe02 objc_exception_throw + 50
2   CoreFoundation                      0x01d822b6 __NSFastEnumerationMutationHandler + 166
3   CoreData                            0x018a0a2e -[NSManagedObjectContext executeFetchRequest:error:] + 3758
4   Dream11                             0x004c0e00 +[KonotorCustomProperty getUnuploadedProperties] + 237
5   Dream11                             0x004be45c __44+[HLCoreServices uploadUnuploadedProperties]_block_invoke + 166
6   libdispatch.dylib                   0x05b99377 _dispatch_call_block_and_release + 15
7   libdispatch.dylib                   0x05bbc9cd _dispatch_client_callout + 14
8   libdispatch.dylib                   0x05ba2985 _dispatch_root_queue_drain + 1008
9   libdispatch.dylib                   0x05ba258e _dispatch_worker_thread3 + 115
10  libsystem_pthread.dylib             0x05efc270 _pthread_wqthread + 1050
11  libsystem_pthread.dylib             0x05ef9f82 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException
